### ISSUE TITLE
Won't install on Windows

### ISSUE THREAD

**Issue by Zalexanninev15** [Azzy380/apafy#1]
Good day. I'm trying to install the library in PyCharm, but it gives me an error and advises me to do it via cmd, after activating venv. The error remains. How to solve it?

```(venv) C:\Users\makss>pip install apafy
Collecting apafy
  Using cached apafy-0.5.6.1.tar.gz (34 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "D:\Temp\pip-install-psojl342\apafy_5726b448c3794a3b9f02a3f726990627\apafy\pafy.py", line 48, in <module>
          import youtube_dl
      ModuleNotFoundError: No module named 'youtube_dl'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\Temp\pip-install-psojl342\apafy_5726b448c3794a3b9f02a3f726990627\setup.py", line 13, in <module>
          from apafy import __version__
        File "D:\Temp\pip-install-psojl342\apafy_5726b448c3794a3b9f02a3f726990627\apafy\__init__.py", line 7, in <module>
          from .pafy import new
        File "D:\Temp\pip-install-psojl342\apafy_5726b448c3794a3b9f02a3f726990627\apafy\pafy.py", line 51, in <module>
          raise ImportError(
      ImportError: pafy: youtube-dl not found; you can use the internal backend by setting the environmental variable PAFY_BACKEND to "internal". It is not enabled by default because it is not as well maintained as the youtube-dl backend.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.```

**Comment by Zalexanninev15** [comment]
Problem solved, I just didn't notice youtube-dl first, I use yt-dlp myself

**Comment by Azzy380** [comment]
Generally, this is version just for my use in replit (cause their system always was downloading wrong library). It is just changed package name and fixed dislikes error. I released it for everyone so they can easily fix dislikes on replit, but don't plan updating it.

If you don't use replit it is better to use pafy-tsml which is exactly the same but uses same package name as pafy.
